### ISSUE TITLE
make recipe for running tests and cleaning

### ISSUE THREAD

**Issue by clbarnes** [funkey/gunpowder#26]
I get a test failure due to a directory not existing, when running `python2 tests/test_suite.py` - not sure if I'm doing something wrong.

```
======================================================================
ERROR: test_output (cases.tensorflow_train.TestTensorflowTrain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cbarnes/work/synapse_detection/gunpowder/tests/cases/tensorflow_train.py", line 115, in test_output
    batch = pipeline.request_batch(request)
  File "/home/cbarnes/work/synapse_detection/gunpowder/gunpowder/nodes/batch_provider.py", line 139, in request_batch
    batch = self.provide(copy.deepcopy(request))
  File "/home/cbarnes/work/synapse_detection/gunpowder/gunpowder/batch_provider_tree.py", line 45, in provide
    return self.output.request_batch(request)
  File "/home/cbarnes/work/synapse_detection/gunpowder/gunpowder/nodes/batch_provider.py", line 139, in request_batch
    batch = self.provide(copy.deepcopy(request))
  File "/home/cbarnes/work/synapse_detection/gunpowder/gunpowder/nodes/batch_filter.py", line 133, in provide
    self.process(batch, request)
  File "/home/cbarnes/work/synapse_detection/gunpowder/gunpowder/nodes/generic_train.py", line 151, in process
    self.train_step(batch, request)
  File "/home/cbarnes/work/synapse_detection/gunpowder/gunpowder/tensorflow/nodes/train.py", line 189, in train_step
    checkpoint_name)
  File "/home/cbarnes/.pyenv/versions/gp2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1675, in save
    raise exc
ValueError: Parent directory of tf_graph_checkpoint_100 doesn't exist, can't save.
```

Also, tests erroring out leaves a bunch of files scattered in the project root; it would be nice to be able to `make clean` those away, or even more ideally, for `TestCase`s which generate files create a temp directory where all those files go, to be deleted in a `tearDownClass` method.

**Comment by clbarnes** [comment]
> for TestCases which generate files create a temp directory where all those files go, to be deleted in a tearDownClass method.

e.g. https://github.com/clbarnes/gunpowder/blob/7613e7c0e31e4b906c12e0ded46035603ecaccef/tests/cases/provider_test.py

**Comment by funkey** [comment]
Good point with the temporary directory. Can you create a PR against `release-v0.3`? Thanks a lot!

Regarding the failing tensorflow test case, we saw this too on some environments. It might depend on the tensorflow version installed. I'll have a look into it.

**Comment by clbarnes** [comment]
In that case, maybe it's worth pinning the versions in the `requirements.txt` and `setup.py` just to make sure everyone's getting something which works.

**Comment by clbarnes** [comment]
Huh, interestingly that failure goes away when the test class manages the files.
