### ISSUE TITLE
Can't run the cremi example.

### ISSUE THREAD

**Issue by skt9** [funkey/gunpowder#89]
Hi,
 I tried to run the cremi example from: http://funkey.science/gunpowder/tutorial.html.

I did this in a conda environment and ended up with the following error. It comes when calling the **build** function. Does anyone know what to do about this?
```
	ERROR:gunpowder.build:something went wrong during the setup of the pipeline, calling tear down
	Traceback (most recent call last):
	  File "train.py", line 147, in <module>
	    train(200000)
	  File "train.py", line 139, in train
	    with gp.build(pipeline):
	  File "/home/sid/anaconda3/envs/tf-py36-gunpowder/lib/python3.6/site-packages/gunpowder/build.py", line 12, in __enter__
	    self.batch_provider.setup()
	  File "/home/sid/anaconda3/envs/tf-py36-gunpowder/lib/python3.6/site-packages/gunpowder/batch_provider_tree.py", line 17, in setup
	    self.__rec_setup(self.output)
	  File "/home/sid/anaconda3/envs/tf-py36-gunpowder/lib/python3.6/site-packages/gunpowder/batch_provider_tree.py", line 70, in __rec_setup
	    self.__rec_setup(upstream_provider)
	  File "/home/sid/anaconda3/envs/tf-py36-gunpowder/lib/python3.6/site-packages/gunpowder/batch_provider_tree.py", line 70, in __rec_setup
	    self.__rec_setup(upstream_provider)
	  File "/home/sid/anaconda3/envs/tf-py36-gunpowder/lib/python3.6/site-packages/gunpowder/batch_provider_tree.py", line 70, in __rec_setup
	    self.__rec_setup(upstream_provider)
	  [Previous line repeated 4 more times]
	  File "/home/sid/anaconda3/envs/tf-py36-gunpowder/lib/python3.6/site-packages/gunpowder/batch_provider_tree.py", line 71, in __rec_setup
	    provider.setup()
	  File "/home/sid/anaconda3/envs/tf-py36-gunpowder/lib/python3.6/site-packages/gunpowder/batch_provider_tree.py", line 17, in setup
	    self.__rec_setup(self.output)
	  File "/home/sid/anaconda3/envs/tf-py36-gunpowder/lib/python3.6/site-packages/gunpowder/batch_provider_tree.py", line 70, in __rec_setup
	    self.__rec_setup(upstream_provider)
	  File "/home/sid/anaconda3/envs/tf-py36-gunpowder/lib/python3.6/site-packages/gunpowder/batch_provider_tree.py", line 70, in __rec_setup
	    self.__rec_setup(upstream_provider)
	  File "/home/sid/anaconda3/envs/tf-py36-gunpowder/lib/python3.6/site-packages/gunpowder/batch_provider_tree.py", line 71, in __rec_setup
	    provider.setup()
	  File "/home/sid/anaconda3/envs/tf-py36-gunpowder/lib/python3.6/site-packages/gunpowder/nodes/hdf5like_source_base.py", line 73, in setup
	    with self._open_file(self.filename) as data_file:
	  File "/home/sid/anaconda3/envs/tf-py36-gunpowder/lib/python3.6/site-packages/gunpowder/nodes/hdf5_source.py", line 39, in _open_file
	    return h5py.File(filename, 'r')
	  File "/home/sid/anaconda3/envs/tf-py36-gunpowder/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
	    swmr=swmr)
	  File "/home/sid/anaconda3/envs/tf-py36-gunpowder/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
	    fid = h5f.open(name, flags, fapl=fapl)
	  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
	  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
	  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
	OSError: Unable to open file (truncated file: eof = 149520384, sblock->base_addr = 0, stored_eof = 1476647581)

```

The conda environment I have installed has python=3.6,  scikit-image==0.14.2, numpy==1.16, tensorflow-gpu==1.14.0,	Nvidia Driver Version: 410.78       CUDA Version: 10.0.

As this is run on the examples provided by the cremi dataset, sample_A_padded_20160501.hdf, it seems a bit strange. Maybe someone can point out my mistake. 

Thank you.

**Comment by funkey** [comment]
Sorry for the late reply.

We have just written two new tutorials, [one of them](http://funkey.science/gunpowder/tutorial_simple_pipeline.html) covering the basics of how to set up a pipeline in much more detail than the example you used. I hope you will find it useful.

Regarding the error you observed, that seems to be related to `h5py`. At a first glance, it looks as if the file you use is corrupted (judging from the `truncated file` part of the error message). But who knows, HDF5 does not stop surprising us in unexpected ways...

I will close for now as this does not seem to be a `gunpowder` related issue. Happy to reopen if a case can be made that it is.
